import 'dart:typed_data';
import 'dart:ui' as ui;
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:printing/printing.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:url_launcher/url_launcher.dart';
import 'treasury.dart';
import 'entry_editor.dart';
import 'report_pdf.dart';

class Workspace extends StatefulWidget {
  const Workspace({super.key,required this.repo,required this.profile});final TreasuryRepository repo;final Json profile;
  @override State<Workspace> createState()=>_WorkspaceState();
}
class _WorkspaceState extends State<Workspace> with WidgetsBindingObserver {
  DateTime month=DateTime(today().year,today().month);int section=0,generation=0;bool loading=true,working=false;String? error,accessError;Json? report,settings;
  List<Json> members=[],companions=[],drafts=[],activities=[];Json? liveProfile;
  Json get profile=>liveProfile??widget.profile;String query='',kind='all';
  bool get writable=>accessError==null && ['admin','treasurer'].contains(profile['role']);
  bool get closed=>report?['closure']!=null;
  @override void initState(){super.initState();WidgetsBinding.instance.addObserver(this);reload();}
  @override void dispose(){generation++;WidgetsBinding.instance.removeObserver(this);super.dispose();}
  @override void didChangeAppLifecycleState(AppLifecycleState state){if(state==AppLifecycleState.resumed)reload();}
  Future<void> reload()async{
    final ticket=++generation;setState((){loading=true;error=null;});
    try{
      final access=await widget.repo.profile();
      final s=await widget.repo.settings();
      final result=await Future.wait<dynamic>([s==null||period(month).compareTo(s['start_month'])<0?Future<Json>.value({'configured':false}):widget.repo.report(month),widget.repo.all('treasury_members'),widget.repo.companions(),widget.repo.all('treasury_entries',status:'draft'),widget.repo.client.rpc('treasury_activities')]);
      if(!mounted||ticket!=generation)return;
      setState((){liveProfile=access;settings=s;report=result[0];members=result[1];companions=result[2];drafts=result[3];activities=rows(result[4]);accessError=null;});
    }catch(e){if(mounted&&ticket==generation){setState((){error=message(e);if(e is FormatException){accessError=error;report=null;members=[];companions=[];drafts=[];activities=[];}});}}
    finally{if(mounted&&ticket==generation)setState(()=>loading=false);}
  }
  void notify(String text){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(text)));}
  Future<void> task(Future<void> Function() action)async{if(working)return;setState(()=>working=true);try{await action();}catch(e){notify(message(e));}finally{if(mounted)setState(()=>working=false);}}
  Future<void> edit([Json? entry])async{
    if(settings==null || !writable)return;
    final result=await Navigator.push<bool>(context,MaterialPageRoute(builder:(_)=>EntryEditor(repo:widget.repo,month:month,settings:settings!,members:members,companions:companions,entry:entry)));
    if(result==true&&mounted){notify('Movimiento guardado.');await reload();}
  }
  Future<void> chooseMonth()async{
    var year=month.year;
    final value=await showDialog<DateTime>(context:context,builder:(c)=>StatefulBuilder(builder:(c,set)=>AlertDialog(title:Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[IconButton(tooltip:'Año anterior',onPressed:()=>set(()=>year--),icon:const Icon(Icons.chevron_left)),Text('$year'),IconButton(tooltip:'Año siguiente',onPressed:()=>set(()=>year++),icon:const Icon(Icons.chevron_right))]),content:SizedBox(width:340,child:Wrap(spacing:6,runSpacing:6,children:List.generate(12,(i)=>SizedBox(width:88,child:OutlinedButton(onPressed:()=>Navigator.pop(c,DateTime(year,i+1)),child:Text(DateFormat('MMM','es').format(DateTime(year,i+1)))))))))));
    if(value!=null&&mounted){setState(()=>month=value);await reload();}
  }
  Future<String?> ask(String title,String label,{bool password=false}) async {
    final controller=TextEditingController();
    final value=await showDialog<String>(context:context,builder:(c)=>AlertDialog(title:Text(title),content:TextField(controller:controller,obscureText:password,decoration:InputDecoration(labelText:label),maxLines:password?1:3),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(c,controller.text),child:const Text('Continuar'))]));
    // Route disposal follows its reverse animation; avoid disposing a focused controller early.
    await Future<void>.delayed(const Duration(milliseconds:300));controller.dispose();return value;
  }
  Future<void> account(String action)async{
    if(action=='logout'){await task(()async{await widget.repo.client.auth.signOut(scope:SignOutScope.local);});}
    if(action=='password'){
      final value=await ask('Cambiar contraseña','Nueva contraseña (mínimo 12 caracteres)',password:true);if(value==null)return;
      if(value.length<12){notify('Utiliza al menos 12 caracteres.');return;}
      final confirmation=await ask('Confirmar contraseña','Repite la nueva contraseña',password:true);if(confirmation!=value){notify('Las contraseñas no coinciden.');return;}
      await task(()async{await widget.repo.client.auth.updateUser(UserAttributes(password:value));notify('Contraseña actualizada.');});
    }
    if(action=='admin'){await launchUrl(Uri.parse('https://narcoticos-anonimos-azure.vercel.app/admin/'),mode:LaunchMode.externalApplication);}
    if(action=='initial')await initialFunds();
  }
  Future<void> initialFunds() async {
    final general=TextEditingController(text:settings==null?'':((settings!['opening_general'] as num)/100).toStringAsFixed(2));
    final local=TextEditingController(text:settings==null?'':((settings!['opening_rent'] as num)/100).toStringAsFixed(2));
    final note=TextEditingController(text:settings?['note']??''),reason=TextEditingController();DateTime start=settings==null?month:DateTime.parse(settings!['start_month']);String? feedback;bool saving=false;
    await showDialog<void>(context:context,barrierDismissible:false,builder:(c)=>StatefulBuilder(builder:(c,set)=>PopScope(canPop:!saving,child:AlertDialog(title:Text(settings==null?'Registrar fondos iniciales':'Corregir fondos iniciales'),content:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[const Text('Registra dinero físico verificado. General: gastos del grupo. Local: dinero reservado para arriendo. No incluyas deudas pendientes.'),TextButton(onPressed:saving?null:()async{final d=await showDatePicker(context:c,initialDate:start,firstDate:DateTime(2013),lastDate:today());if(d!=null)set(()=>start=DateTime(d.year,d.month));},child:Text('Mes de inicio: ${period(start).substring(0,7)}')),TextField(controller:general,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Gastos del grupo · USD')),const SizedBox(height:12),TextField(controller:local,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Apartado para el local · USD')),const SizedBox(height:12),TextField(controller:note,decoration:const InputDecoration(labelText:'Nota')),if(settings!=null)...[const SizedBox(height:12),const Text('La corrección recalcula los saldos y reabre meses cerrados. Revisa después los informes.'),TextField(controller:reason,decoration:const InputDecoration(labelText:'Motivo de la corrección'))],if(feedback!=null)Text(feedback!,style:const TextStyle(color:Colors.red))])),actions:[TextButton(onPressed:saving?null:()=>Navigator.pop(c),child:const Text('Cancelar')),FilledButton(onPressed:saving?null:()async{try{final a=cents(general.text),b=cents(local.text);if(settings!=null&&reason.text.trim().length<5)throw const FormatException('Explica el motivo de la corrección.');set(()=>saving=true);await widget.repo.command(settings==null?'setup':'initial_update',{'start_month':period(start),'opening_general':a,'opening_rent':b,'note':note.text.trim(),'reason':reason.text.trim()});if(c.mounted)Navigator.pop(c);await reload();}catch(e){if(c.mounted)set((){feedback=message(e);saving=false;});}},child:Text(saving?'Guardando…':'Guardar'))]))));
    await Future<void>.delayed(const Duration(milliseconds:300));for(final controller in [general,local,note,reason]){controller.dispose();}
  }
  Future<void> export()async{
    if(report?['configured']!=true)return;
    final photos=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Informe mensual'),content:const Text('Ingresos y egresos se presentan separados. ¿Deseas incluir también las fotografías?'),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Sin fotos')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Con fotos'))]));if(photos==null)return;
    await task(()async{
      final fresh=Json.from(await widget.repo.client.rpc('treasury_prepare_report',params:{'p_month':period(month),'p_format':'pdf','p_include_dues':true}) as Map);
      final evidence=<String,Uint8List>{};var failed=0,totalBytes=0;
      if(photos){for(final e in rows(fresh['entries']).where((e)=>e['status']=='posted'&&e['receipt_path']!=null)){
        final path=e['receipt_path'].toString();if(path.toLowerCase().endsWith('.pdf')){failed++;continue;}
        try{final bytes=await widget.repo.client.storage.from('treasury-receipts').download(path).timeout(const Duration(seconds:20));if(bytes.length>10485760){failed++;continue;}final codec=await ui.instantiateImageCodec(bytes,targetWidth:1200,allowUpscaling:false);final frame=await codec.getNextFrame();final optimized=await frame.image.toByteData(format:ui.ImageByteFormat.png);frame.image.dispose();codec.dispose();if(optimized==null||totalBytes+optimized.lengthInBytes>20971520){failed++;continue;}final image=optimized.buffer.asUint8List(optimized.offsetInBytes,optimized.lengthInBytes);totalBytes+=image.length;evidence[path]=image;}catch(_){failed++;}
      }}
      final bytes=await reportPdf(fresh,evidence:evidence,includeEvidence:photos);await Printing.sharePdf(bytes:bytes,filename:'Tesoreria_${period(month).substring(0,7)}.pdf');if(failed>0)notify('$failed comprobante(s) no pudieron incluirse. Consulta sus originales desde el movimiento.');
    });
  }
  Future<void> receipt(Json entry)async{
    final path=entry['receipt_path'];if(path==null)return;
    await task(()async{final data=await widget.repo.client.storage.from('treasury-receipts').download(path).timeout(const Duration(seconds:20));if(!mounted)return;if(path.toString().endsWith('.pdf')){await Printing.sharePdf(bytes:data,filename:'Comprobante.pdf');}else{await showDialog<void>(context:context,builder:(c)=>Dialog(child:Column(mainAxisSize:MainAxisSize.min,children:[Flexible(child:InteractiveViewer(child:Image.memory(data,errorBuilder:(_,e,s)=>const Padding(padding:EdgeInsets.all(24),child:Text('No se pudo mostrar esta imagen.'))))),TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Cerrar'))])));}});
  }
  Future<void> detail(Json entry)async{
    await showModalBottomSheet<void>(context:context,isScrollControlled:true,useSafeArea:true,builder:(c)=>Padding(padding:const EdgeInsets.all(24),child:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text(money(entry['amount_cents']),style:const TextStyle(fontSize:36,fontWeight:FontWeight.bold)),Text('${entry['entry_date']} · ${entry['status']}'),Text(categories[entry['category']]??entry['category']),const SizedBox(height:12),Text(entry['description']??''),Text(entry['fund']=='rent'?'Fondo para el local':'Fondo general'),if(entry['no_receipt_reason']?.toString().isNotEmpty==true)Text('Sin comprobante: ${entry['no_receipt_reason']}'),if(entry['receipt_path']!=null)TextButton.icon(onPressed:()=>receipt(entry),icon:const Icon(Icons.receipt_long),label:const Text('Abrir comprobante')),if(writable&&entry['status']!='void')FilledButton(onPressed:(){Navigator.pop(c);edit(entry);},child:Text(entry['status']=='draft'?'Completar borrador':'Corregir con motivo')),if(writable&&entry['status']=='posted')TextButton(onPressed:()async{Navigator.pop(c);final reason=await ask('Anular movimiento','Motivo de la anulación');if(reason==null)return;await task(()async{await widget.repo.command('void',{'id':entry['id'],'version':entry['version'],'reason':reason});await reload();});},child:const Text('Anular indicando el motivo'))]))));
  }
  Widget metric(String label,Object? amount,{bool dark=false})=>Card(color:dark?const Color(0xff102d50):Colors.white,child:Padding(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(label,style:TextStyle(color:dark?Colors.white70:Colors.blueGrey,fontSize:13)),const SizedBox(height:8),Text(money(amount),style:TextStyle(fontSize:30,fontWeight:FontWeight.bold,color:dark?Colors.white:const Color(0xff102d50)))])));
  Widget entryTile(Json e)=>Card(child:ListTile(contentPadding:const EdgeInsets.symmetric(horizontal:16,vertical:8),leading:CircleAvatar(backgroundColor:e['kind']=='income'?Colors.green.shade50:Colors.orange.shade50,child:Icon(e['kind']=='income'?Icons.south_west:Icons.north_east,color:e['kind']=='income'?Colors.green.shade800:Colors.brown)),title:Text(e['description']?.toString().isNotEmpty==true?e['description']:'Comprobante por completar'),subtitle:Text('${e['entry_date']} · ${categories[e['category']]}\n${e['status']=='draft'?'Borrador':e['status']=='void'?'Anulado':e['fund']=='rent'?'Local':'General'}'),trailing:Text(money(e['amount_cents']),style:const TextStyle(fontWeight:FontWeight.bold)),onTap:()=>detail(e)));
  List<Widget> overview(){final funds=rows(report?['funds']);final total=funds.fold<num>(0,(n,f)=>n+(f['closing'] as num));return [metric('DINERO DISPONIBLE',total,dark:true),for(final f in funds)metric(f['fund']=='rent'?'Apartado para el local':'Para gastos del grupo',f['closing']),const Padding(padding:EdgeInsets.symmetric(vertical:12),child:Text('Las cuotas pendientes y los borradores no se suman al dinero disponible.')),if(writable)FilledButton.icon(onPressed:working?null:()=>edit(),icon:const Icon(Icons.add),label:const Text('Registrar ingreso o egreso')),const SizedBox(height:16),Text(closed?'Mes cerrado':'Mes abierto',style:const TextStyle(fontWeight:FontWeight.bold)),for(final label in ['opening','income','expense'])ListTile(title:Text({'opening':'Saldo al inicio','income':'Ingresos del mes','expense':'Egresos del mes'}[label]!),trailing:Text(money(funds.fold<num>(0,(n,f)=>n+(f[label] as num))))),OutlinedButton.icon(onPressed:working?null:export,icon:const Icon(Icons.picture_as_pdf_outlined),label:const Text('Compartir informe PDF')),const SizedBox(height:20),const Text('Movimientos recientes',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),...rows(report?['entries']).reversed.take(5).map(entryTile)];}
  List<Widget> movementView()=>[TextField(decoration:const InputDecoration(labelText:'Buscar movimiento',prefixIcon:Icon(Icons.search)),onChanged:(v)=>setState(()=>query=v.toLowerCase())),const SizedBox(height:12),SegmentedButton<String>(segments:const [ButtonSegment(value:'all',label:Text('Todos')),ButtonSegment(value:'income',label:Text('Ingresos')),ButtonSegment(value:'expense',label:Text('Egresos'))],selected:{kind},onSelectionChanged:(v)=>setState(()=>kind=v.first)),const SizedBox(height:12),...rows(report?['entries']).reversed.where((e)=>(kind=='all'||e['kind']==kind)&&'${e['description']} ${e['member_name']} ${categories[e['category']]}'.toLowerCase().contains(query)).map(entryTile),if(drafts.isNotEmpty)...[const SizedBox(height:20),const Text('BORRADORES · no afectan el saldo',style:TextStyle(fontWeight:FontWeight.bold)),...drafts.map(entryTile)]];
  List<Widget> duesView()=>[const Text('Aportes para el local',style:TextStyle(fontSize:24,fontWeight:FontWeight.bold)),const Text('Los pagos confirmados ya están incluidos en el fondo del local.'),...rows(report?['dues']).map((d)=>Card(child:ListTile(leading:const Icon(Icons.person_outline),title:Text(d['name']),subtitle:Text('Cuota: ${money(d['expected'])}\nRecibido: ${money(d['paid'])} · Pendiente: ${money(((d['expected'] as num)-(d['paid'] as num)).clamp(0,100000000))}')))),const SizedBox(height:20),const Text('Pendientes de actividades',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),const Text('Datos informativos: no forman parte del dinero disponible hasta que se cobra. En esta primera versión, registra sus pagos desde la web.'),...activities.map((a)=>Card(child:ListTile(title:Text(a['name']),subtitle:Text('${a['activity']}\nPor cobrar: ${money(a['pending_cents'])}'))))];
  Future<void> audit()async{await task(()async{final data=await widget.repo.client.from('treasury_audit').select('action,actor_name,happened_at').order('id',ascending:false).limit(50);if(!mounted)return;await showModalBottomSheet<void>(context:context,isScrollControlled:true,useSafeArea:true,builder:(c)=>SizedBox(height:MediaQuery.sizeOf(c).height*.8,child:ListView(padding:const EdgeInsets.all(20),children:[const Text('Últimos 50 cambios',style:TextStyle(fontSize:24,fontWeight:FontWeight.bold)),...data.map((a)=>ListTile(leading:const Icon(Icons.history),title:Text(a['actor_name']??'Usuario'),subtitle:Text('${a['action']} · ${a['happened_at']}')))])));});}
  List<Widget> more()=>[ListTile(leading:const Icon(Icons.help_outline),title:const Text('Cómo utilizar Tesorería'),subtitle:const Text('General: séptimas y otros ingresos. Local: aportes para arriendo. Borrador: registro por completar, no suma dinero. Confirmar: incorpora el movimiento al saldo. Corregir: conserva el historial.'),isThreeLine:true),ListTile(leading:const Icon(Icons.history),title:const Text('Historial de cambios'),onTap:working?null:audit),ListTile(leading:const Icon(Icons.language),title:const Text('Abrir Tesorería web'),subtitle:const Text('Gestionar actividades, compañeros y cierres mensuales'),onTap:()=>launchUrl(Uri.parse('https://narcoticos-anonimos-azure.vercel.app/tesoreria/'),mode:LaunchMode.externalApplication)),if(writable)ListTile(leading:const Icon(Icons.account_balance),title:const Text('Corregir fondos iniciales'),onTap:working?null:initialFunds),if(profile['role']=='admin')ListTile(leading:const Icon(Icons.manage_accounts),title:const Text('Administrar usuarios'),subtitle:const Text('Abrir el panel administrativo existente'),onTap:()=>account('admin'))];
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Tesorería'),actions:[IconButton(tooltip:'Actualizar',onPressed:loading||working?null:reload,icon:const Icon(Icons.refresh)),PopupMenuButton<String>(tooltip:'Mi perfil',onSelected:account,itemBuilder:(_)=>[PopupMenuItem<String>(enabled:false,child:Text('${profile['display_name'] ?? widget.repo.client.auth.currentUser?.email}\n${{'admin':'Administrador','treasurer':'Tesorería','auditor':'Consulta'}[profile['role']]}')),const PopupMenuItem(value:'password',child:Text('Cambiar contraseña')),const PopupMenuItem(value:'logout',child:Text('Cerrar sesión'))])]),body:SafeArea(child:Column(children:[Padding(padding:const EdgeInsets.fromLTRB(20,8,20,8),child:OutlinedButton.icon(onPressed:working?null:chooseMonth,icon:const Icon(Icons.date_range),label:Text(DateFormat('MMMM yyyy','es').format(month)))),if(working)const LinearProgressIndicator(),Expanded(child:loading?const Center(child:CircularProgressIndicator()):RefreshIndicator(onRefresh:reload,child:ListView(padding:const EdgeInsets.fromLTRB(20,0,20,24),children:error!=null?[Text(error!,style:const TextStyle(color:Colors.red)),FilledButton(onPressed:reload,child:const Text('Reintentar'))]:report?['configured']!=true?[const SizedBox(height:24),Text(settings==null?'Registra los fondos iniciales para comenzar.':'Este mes es anterior al inicio de Tesorería.'),if(writable&&settings==null)FilledButton(onPressed:initialFunds,child:const Text('Registrar fondos'))]:section==0?overview():section==1?movementView():section==2?duesView():more()))) ])),bottomNavigationBar:NavigationBar(selectedIndex:section,onDestinationSelected:(i)=>setState(()=>section=i),destinations:const [NavigationDestination(icon:Icon(Icons.dashboard_outlined),label:'Resumen'),NavigationDestination(icon:Icon(Icons.swap_vert),label:'Movimientos'),NavigationDestination(icon:Icon(Icons.people_outline),label:'Aportes'),NavigationDestination(icon:Icon(Icons.more_horiz),label:'Más')]));
}
